### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by ICONGraphs** [kryptopoo/xcallscan#15]
Hey, Rook from ICON Foundation here. We are transitioning from xCall to "ICON General Message Passing", if you can please update the attached logo.
[ICON Network.zip](https://github.com/kryptopoo/xcallscan/files/14251402/ICON.Network.zip)
Cheers

**Comment by kryptopoo** [comment]
@ICONGraphs I hot-updated the logo on production, so I'm going to close this issue.
